version: '3'

services:
  gameserver:
    build:
      context: .
      dockerfile: 'Dockerfile.dev'
    image: golang-multiplayer-server:latest
    container_name: golang-multiplayer-server
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./:/go/src
    command: 'CompileDaemon --build="go build -o ./build/server"
      --command=./build/server'
